name: ar
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - pyarrow
  - matplotlib
  - scikit-learn
  - jupyterlab
  - ipykernel
  - python-dateutil
  - pip:
      - plotly
      - streamlit
